joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
  publish_rate: 50

diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  publish_rate: 50
  left_wheel_names: ["left_wheel_joint"]
  right_wheel_names: ["right_wheel_joint"]
  wheel_separation: 0.4  # adjust based on your bot
  wheel_radius: 0.1      # adjust based on your wheels
  base_frame_id: base_link
  odom_frame_id: odom
  enable_odom_tf: true
  open_loop: false
